### ISSUE TITLE
Warnings and Errors on Brake (Release 5)

### ISSUE THREAD

**Issue by Thizzed** [arne182/ArnePilot#764]
Clean install, after engaging and then braking the alarm sound goes off and errors pop up in my car.  No disengage on braking causing this? Never had this issue on previous releases. Corolla 2021

**Comment by arne182** [comment]
Thanks. This just means that you need to manually flash the panda with the firmware to enable steering assist. 
pkill -f boardd; cd /data/openpilot/panda/board; make; reboot
Should get it working as expected

**Comment by Stupefacient** [comment]
If you have a comma2 you need to flash the panda while the device in the car or else won’t work fully

**Comment by Thizzed** [comment]
Thank you Arne and Brian appreciate it
